version: '3'

vars:
  CONFIG_DIR: '~/.config/mihomo'
  CONFIG_FILE: '{{.CONFIG_DIR}}/config.yaml'
  CONFIG_URL: '{{default "http://your-domain.com/your-config" .CLASH_CONFIG_URL}}'

tasks:
  update-mihomo-config:
    desc: 从远程获取mihomo配置并更新本地文件
    cmds:
      # 确保配置目录存在
      - mkdir -p {{.CONFIG_DIR}}
      # 下载配置文件并格式化
      - curl -L -o {{.CONFIG_FILE}} "{{.CONFIG_URL}}"
    silent: false
    preconditions:
      - sh: "command -v curl"
        msg: "curl is not installed"

  download-geoip:
    desc: 下载Country.mmdb地理数据库文件
    cmds:
      # 确保配置目录存在
      - mkdir -p {{.CONFIG_DIR}}
      # 下载Country.mmdb文件
      - curl -L -o {{.CONFIG_DIR}}/Country.mmdb "https://github.com/Dreamacro/maxmind-geoip/releases/download/20250512/Country.mmdb"
    silent: false
    preconditions:
      - sh: "command -v curl"
        msg: "curl is not installed"